version: '3.4'

networks:
  backend:
   driver: bridge

services:
  vermilion.webapi:
    image: ${DOCKER_REGISTRY-}vermilionwebapi
    container_name: vermilion-api
    build:
      context: .
      dockerfile: Vermilion.WebApi/Dockerfile
    ports:
    - "8080:80"
    depends_on: 
    - vermilion-db
    networks:
    - backend

  vermilion-db:
   container_name: "vermilion-database"
   image: postgres:latest
   ports:
   - "5432:5432"
   environment:
    POSTGRES_DB: "vermilion-db"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_HOST: "vermilionapi"
   volumes:
   - postgres-data:/var/lib/postgresql
   networks:
   - backend

  vermilion-cache:
     image: redis:latest
     container_name: vermilion-cache
     restart: always
     ports:
        - 6379:6379
     networks:
      - backend
volumes:
  postgres-data: {}
 